import type { Metadata } from "next";
import { Inter, Epilogue, Raleway } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import Header from "@/components/Header";
import BuyNowFormModal from "@/components/BuyNowFormModal";

const inter = Inter({ subsets: ["latin"] });

const raleway = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Watches",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <Header />
        {children}
        <BuyNowFormModal />
      </body>
    </html>
  );
}
